{% set name = "flowkit" %}
{% set version = "0.9.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/FlowKit-{{ version }}.tar.gz
  sha256: 8edad808845507bd0c83ddfc36e6dde31e2068c1a4d8cf01e5806c718fb46128

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python
    - anytree >=2.6
    - bokeh >=2,<3
    - flowio >=1.0.1,<1.1
    - flowutils >=1,<1.1
    - lxml >=4.4
    - matplotlib-base >=3.1
    - networkx >=2.3
    - numpy >=1.20
    - pandas >=1.1
    - psutil >=5.8scipy
    - seaborn
    - statsmodels

test:
  imports:
    - flowkit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/whitews/flowkit
  dev_url: https://github.com/vivekhaz/flowkit
  doc_url: https://vivekhaz.github.io/repo/flowkit
  summary: Flow Cytometry Toolkit
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - vivekhaz 
